version: "3.7"
services:
  api-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DBNAME=interview
    depends_on:
      database:
        condition: service_healthy  # Wait for the database service to be healthy before starting the API service
  database:
    image: postgres:15.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DBNAME=interview
    volumes:
      - ./postgresql/test.sh:/postgresql/init-database.sh
      - ./postgresql/data:/var/lib/postgresql/data
    command: ["/postgresql/init-database.sh"]
    healthcheck:  # Define health checks for the PostgreSQL service
      test: ["CMD-SHELL", "pg_isready -q -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
